---
- hosts: "workstation"
  roles:
    - common
  tasks:
    - name: Add users
      include_tasks: roles/common/tasks/users.yml

- hosts: "workstation"
  roles:
    - workstation
  tasks:
    - name: Setup development
      include_tasks: roles/workstation/tasks/development.yml
    - name: Setup terminals
      include_tasks: roles/workstation/tasks/terminal.yml
    - name: Setup filemanagers
      include_tasks: roles/workstation/tasks/filemanager.yml
    - name: Setup pass
      include_tasks: roles/workstation/tasks/pass.yml
    - name: Setup nvim
      include_tasks: roles/workstation/tasks/nvim.yml
    - name: Setup tmux
      include_tasks: roles/workstation/tasks/tmux.yml
