# Hyprland configuration

# (Paste the contents of the original hyprland/tasks/main.yml here) 

- name: Install Hyprland
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - sddm
    - hyprland
    - mako
    - libnotify
    - kitty
    - uwsm
    - rofi-wayland
    - xdg-desktop-portal-hyprland
    - qt5-wayland
    - qt6-wayland
    - grim
    - slurp
    - swww
    - polkit-gnome
    - gnome-keyring
    - networkmanager
    - network-manager-applet
    - brightnessctl
    - pavucontrol

- name: Enable and start sddm
  become: true
  ansible.builtin.systemd:
    name: sddm
    state: started
    enabled: yes
    daemon_reload: yes

- name: Enable and start NetworkManager
  become: true
  ansible.builtin.systemd:
    name: NetworkManager
    state: started
    enabled: yes
    daemon_reload: yes

- name: Install swww system service file
  become: true
  ansible.builtin.copy:
    src: swww.service
    dest: /etc/systemd/system/swww.service
    mode: '0644'

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start swww system service
  become: true
  ansible.builtin.systemd:
    name: swww.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Install Hyprland Eco system
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - waybar
    - hyprpaper
    - hyprpicker
    - hypridle
    - hyprlock
    - hyprcursor
    - hyprpolkitagent

- name: Theme dependencies
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - ttf-fantasque-sans-mono
    - ttf-fantasque-nerd 

