---
# Browser configuration

- name: Install Browsers
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop:
    - firefox
    - qutebrowser
    - yt-dlp

#- name: Install Zen Browser
#  become: yes
#  flatpak:
#    name: app.zen_browser.zen 
