---
# Media tools configuration

- name: Remove default Gnome video (totem)
  become: yes
  pacman:
    name: "{{item}}"
    state: absent
  loop:
    - totem
    - totem-plugins

#- name: Install media tools
#  become: yes
#  community.general.flatpak:
#    name:
#      - org.videolan.VLC
#      - com.ktechpit.wonderwall
#      - tech.feliciano.pocket-casts

- name: Install media tools
  become: yes
  pacman:
    name:
      - vlc

- name: Install music tools
  become: yes
  pacman:
    name:
      - mpd
      - ncmpcpp
      - mpc
      - beets
      - python-requests

- name: Ensure proper locale for music applications
  become: true
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "LC_ALL=en_US.UTF-8"
    state: present
    create: yes

- name: Generate en_US.UTF-8 locale
  become: true
  ansible.builtin.command: locale-gen en_US.UTF-8
  args:
    creates: /usr/lib/locale/en_US.UTF-8

- name: Stop and disable system mpd service if running
  become: true
  ansible.builtin.systemd:
    name: mpd.service
    state: stopped
    enabled: no

- name: Create MPD user service directory
  become: true
  become_user: ritchie
  ansible.builtin.file:
    path: "~/.config/systemd/user"
    state: directory
    mode: '0755'

- name: Copy mpd user service file
  become: true
  become_user: ritchie
  ansible.builtin.copy:
    src: ../../desktop/tasks/files/mpd.service
    dest: ~/.config/systemd/user/mpd.service
    mode: '0644'

- name: Reload user systemd daemon for mpd
  become: true
  become_user: ritchie
  ansible.builtin.command: systemctl --user daemon-reload

- name: Enable and start mpd user service
  become: true
  become_user: ritchie
  ansible.builtin.command: systemctl --user enable --now mpd.service 