---
# Steam configuration

- name: Enable multilib repository for Steam
  become: yes
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?\[multilib\]'
    line: '[multilib]'
    state: present

- name: Enable multilib repository Include line
  become: yes
  lineinfile:
    path: /etc/pacman.conf
    insertafter: '^\[multilib\]'
    regexp: '^#?Include = /etc/pacman.d/mirrorlist'
    line: 'Include = /etc/pacman.d/mirrorlist'
    state: present

- name: Update package database after enabling multilib
  become: yes
  pacman:
    update_cache: yes

- name: Install Steam and dependencies
  become: yes
  pacman:
    name:
      # Steam itself
      - steam
      # Essential fonts
      - ttf-liberation
      # 32-bit graphics drivers (common ones)
      - lib32-mesa
      - lib32-vulkan-icd-loader
      # Audio support
      - lib32-alsa-plugins
      - lib32-pulseaudio
      # Additional libraries Steam may need
      - lib32-gtk3
      - lib32-glibc
      - lib32-gcc-libs
    state: present 