
- name: Add appimage launcher repository
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:appimagelauncher-team/stable

- name: Add Nextcloud repository
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:nextcloud-devs/client

- name: Install core applciations
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - appimagelauncher
    - nextcloud-client
    - wireguard
    - gnome-shell-extension-manager
    - vlc

