- name: Install core tools (debian)
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - pass
    - pass-otp
    - xclip
    - qrencode


#- name: Install auxiliary tools (debian)
#  become: yes
#  apt:
#    name: "{{item}}"
#    state: present
#    update_cache: yes
#  loop:
#    - syncthing
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Bitwarden client (debian)
  become: yes
  flatpak:
    name: com.bitwarden.desktop

