- name: Install Steam
  become: yes
  flatpak:
    name: "{{item}}"
  loop:
    - com.valvesoftware.Steam

- name: Install Steam dependencies
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - fonts-liberation
