# enable multilib
- name: add multilib
  become: yes
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"
  when: ansible_distribution == 'Arch Linux'

- name: add multilib (cont)
  become: yes
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
    regexp: "Include = /etc/pacman.d/mirrorlist"
  when: ansible_distribution == 'Arch Linux'

- name: Install Steam
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop:
    - steam
    - ttf-liberation
  when: ansible_distribution == 'Arch Linux'

- name: Install Steam
  become: yes
  flatpak:
    name: "{{item}}"
  loop:
    - com.valvesoftware.Steam
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Steam dependencies
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - fonts-liberation
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
