---
- name: Install syncthing
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - syncthing
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
