- name: Remove some defaults
  become: true
  pacman:
    name: dolphin
    state: absent

- name: Install Hyprland
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - sddm
    - hyprland
    - mako
    - kitty
    - uwsm
    - dolphin
    - rofi-wayland
    - xdg-desktop-portal-hyprland
    - qt5-wayland
    - qt6-wayland
    - polkit-kde-agent
    - grim
    - slurp
    - swww
    - thunar
    - polkit-gnome
    - gnome-keyring
    - networkmanager
    - nm-applet
    - brightnessctl
    - bluez
    - bluez-utils
    - blueman

- name: Install Hyprland Eco system
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - waybar
    - hyprpaper
    - hyprpicker
    - hypridle
    - hyprlock
    - hyprcursor
    - hyprpolkitagent
