- name: Install Hyprland
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - sddm
    - hyprland
    - mako
    - kitty
    - uwsm
    - rofi-wayland
    - xdg-desktop-portal-hyprland
    - qt5-wayland
    - qt6-wayland
    - polkit-kde-agent
    - grim
    - slurp
    - swww
    - polkit-gnome
    - gnome-keyring
    - networkmanager
    - network-manager-applet
    - brightnessctl
    - bluez
    - bluez-utils
    - blueman

- name: Enable and start NetworkManager
  systemd_service:
    name: NetworkManager
    enabled: true
    state: started

- name: Install swww system service file
  template:
    src: swww-daemon.service.j2
    dest: /etc/systemd/system/swww-daemon.service
    mode: '0644'
  become: true

- name: Enable and start swww system service
  systemd:
    name: swww-daemon
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Install Hyprland Eco system
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - waybar
    - hyprpaper
    - hyprpicker
    - hypridle
    - hyprlock
    - hyprcursor
    - hyprpolkitagent

- name: Theme dependencies 
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop:
    - ttf-fantasque-sans-mono
    - ttf-fantasque-nerd
