- name: Install Hyprland
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - sddm
    - hyprland
    - mako
    - kitty
    - uwsm
    - rofi-wayland
    - xdg-desktop-portal-hyprland
    - qt5-wayland
    - qt6-wayland
    - polkit-kde-agent
    - grim
    - slurp
    - swww
    - polkit-gnome
    - gnome-keyring
    - networkmanager
    - network-manager-applet
    - brightnessctl
    - bluez
    - bluez-utils
    - blueman

- name: Enable and start NetworkManager
  systemd_service:
    name: NetworkManager
    enabled: true
    state: started

- name: Install Hyprland Eco system
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - waybar
    - hyprpaper
    - hyprpicker
    - hypridle
    - hyprlock
    - hyprcursor
    - hyprpolkitagent

- name: Theme dependencies 
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop:
    - ttf-fantasque-sans-mono
    - ttf-fantasque-nerd
