---
- name: Install pass
  become: true
  pacman:
    name: pass
    state: present
    update_cache: yes

- name: Install pass-otp
  become: true
  pacman:
    name: pass-otp
    state: present
    update_cache: yes 

- name: Install pass dependencies
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - wl-clipboard
    - zbar

- name: Install PassFF host app for Firefox
  shell: curl -sSL https://codeberg.org/PassFF/passff-host/releases/download/latest/install_host_app.sh | bash -s -- firefox
  args:
    creates: "{{ ansible_env.HOME }}/.mozilla/native-messaging-hosts/passff.json"
  register: passff_install
  changed_when: passff_install.rc == 0
  failed_when: passff_install.rc != 0
