- name: Install lightdm  
  become: true
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - lightdm

- name: Install awesomewm and necessary utilities 
  become: true
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - awesome
    - rofi
    - avahi-daemon
    - libnss-mdns
    - feh
