- name: Remove default Gnome video (totem)
  become: yes
  apt:
    name: "{{item}}"
    state: absent
  loop:
    - totem
    - totem-plugins
  tags:
    - debian

- name: Install media tools
  become: yes
  community.general.flatpak:
    name:
      - org.videolan.VLC
      - com.ktechpit.wonderwall
      - tech.feliciano.pocket-casts

- name: Install music tools
  become: yes
  apt:
    name:
      - mpd
      - ncmpcpp
      - beets
