---
# Development tools setup

- name: Install RVM
  become: no
  shell: "curl -sSL https://get.rvm.io | bash"
  args:
    creates: "{{ ansible_env.HOME }}/.rvm"

- name: Install tmuxinator gem
  become: no
  shell: "source ~/.rvm/scripts/rvm && gem install tmuxinator"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.rvm/gems/ruby-3.2.0/bin/tmuxinator"

- name: Clone TPM repository
  become: no
  git:
    depth: 1
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm" 