---
# Editor setup tasks

- name: Install editor packages
  become: true
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - neovim
    - vim

- name: Install Cursor (AUR)
  kewlfft.aur.aur:
    name: cursor-bin
    use: yay
    state: present 
  become: no

- name: Install Claude Code (AUR)
  kewlfft.aur.aur:
    name: claude-code-bin
    use: yay
    state: present 
  become: no
