---
# System maintenance tasks

- name: Run the equivalent of "pacman -Sy" as a separate step
  become: yes
  community.general.pacman:
    update_cache: true

- name: Update system packages
  become: true
  pacman:
    update_cache: yes
    upgrade: yes 