- name: Install nvim dependencies and nvim build dependencies
  become: true
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    # - neovim
    - ninja-build
    - gettext
    - cmake
    - unzip
    - curl
    - ripgrep
    # - rust-fd-find
    - fonts-jetbrains-mono

- name: 'Remove tmp folder for neovim'
  become: true
  ansible.builtin.file:
    path: /tmp/neovim
    state: absent

- name: Download stable release from the neovim repository
  become: no
  ansible.builtin.git:
    depth: 1
    version: stable
    repo: https://github.com/neovim/neovim
    dest: /tmp/neovim

- name: Build neovim
  become: no
  shell:
    cmd: "make CMAKE_BUILD_TYPE=RelWithDebInfo"
    chdir: /tmp/neovim
  tags:
    - debian

- name: Build neovim package
  become: no
  shell:
    cmd: "cpack -G DEB"
    chdir: /tmp/neovim/build

- name: Install a neovim package
  become: true
  ansible.builtin.apt:
    deb: /tmp/neovim/build/nvim-linux-x86_64.deb
