- name: Install tmux
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - tmux

- name: Clone TPM repository
  become: no
  git:
    depth: 1
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: ~/.tmux/plugins/tpm
