---
- hosts: "workstations"
  tasks:
    - name: 'Complete apt updates'
      include_tasks: roles/common/tasks/apt-update.yml
    - name: 'Complete flatpak updates'
      include_tasks: roles/common/tasks/flatpak-update.yml
