- name: apt-update
  become: true
  apt:
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes

#- name: Update all packages to the latest version
#  become: true
#  apt:
#    update_cache: yes
#    upgrade: full
#    force_apt_get: yes
