---
- hosts: "workstations"
  remote_user: ansible
  roles:
    - system/base
    - system/security
    - workstation
    - desktop
    - applications
    - work
  tasks:
    - name: Setup workstation
      include_tasks: roles/workstation/tasks/main.yml
    - name: Setup nvim
      include_tasks: roles/workstation/tasks/nvim.yml
