- name: Update system
  include_tasks: roles/common/tasks/apt-update.yml

- name: Run the equivalent of "pacman -Sy" as a separate step
  become: yes
  community.general.pacman:
    update_cache: true
  when: ansible_distribution == 'Arch Linux'

