- name: Add the user 'ansible'
  become: yes
  ansible.builtin.user:
    name: ansible
    uid: 1001
    shell: /bin/bash

- name: Set authorized key for ansible
  become: yes
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '../files/onoda.pub') }}"

- name: Install sudo
  become: true
  apt:
    name: sudo
    state: present
    update_cache: yes

- name: Allow the ansible user to sudo
  become: true
  community.general.sudoers:
    name: ansible-as-root
    state: present
    user: ansible
    runas: root
    commands: ALL
