---
- name: Remove conflicting polkit packages
  become: true
  pacman:
    name:
      - ksshaskpass
      - polkit-gnome
    state: absent

- name: Install base system packages
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - polkit-kde-agent
    - curl
    - vim
    - base-devel
    - git
    - zsh
    - nodejs
    - npm
    - fastfetch
    - autorandr
    - syncthing
    # - polkit-gnome
    - seahorse 
