---
# Development packages setup

- name: Install development packages
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - tmux
    - ruby
    - ruby-erb
    - ripgrep
    - fd
    - xclip
    - python-pynvim
    - lazygit 
