---
# File manager configuration

- name: Install Ranger and dependencies
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop:
    - ranger
    - mc
    - atool
    - elinks
    - ffmpegthumbnailer
    - highlight
    - imagemagick
    - lynx
    - mediainfo
    - transmission-cli
    - ueberzug
    - w3m

- name: Install Dolphin
  become: true
  pacman:
    name: dolphin
    state: present 