---
# File manager configuration

- name: Install Ranger and dependencies
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop:
    - ranger
    - mc
    - atool
    - elinks
    - ffmpegthumbnailer
    - highlight
    - imagemagick
    - lynx
    - mediainfo
    - transmission-cli
    - ueberzug
    - w3m

- name: Install Thunar and network browsing support
  become: true
  pacman:
    name: "{{item}}"
    state: present
  loop:
    - thunar
    - thunar-volman
    - gvfs
    - gvfs-smb
    - smbclient
    - cifs-utils
    - libsecret 