---
# User services configuration for ritchie

- name: Enable and start hypridle user service
  become: true
  become_user: ritchie
  ansible.builtin.command: systemctl --user enable --now hypridle.service
  args:
    creates: "~/.config/systemd/user/hypridle.service"

- name: Enable and start syncthing user service
  become: true
  become_user: ritchie
  ansible.builtin.command: systemctl --user enable --now syncthing.service
  args:
    creates: "~/.config/systemd/user/syncthing.service"

- name: Stop mpd user service if running
  become: true
  become_user: ritchie
  ansible.builtin.command: systemctl --user stop mpd.service
  ignore_errors: true

- name: Enable and start mpd user service
  become: true
  become_user: ritchie
  ansible.builtin.command: systemctl --user enable --now mpd.service
  args:
    creates: "~/.config/systemd/user/mpd.service" 