---
- name: Install Firefox
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop:
    - firefox

#- name: Install Zen Browser
#  become: yes
#  flatpak:
#    name: app.zen_browser.zen
