
- name: Install Flatpack
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - flatpak

- name: Add Flathub 
  become: true
  shell:
    cmd: "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
