
- name: Install terminal mail stack (ubuntu)
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - lynx
    - neomutt
    - msmtp
    - isync
    - imapfilter
  tags:
    - ubuntu

- name: Install terminal mail stack (manjaro)
  become: yes
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - lynx
    - neomutt
    - msmtp
    - isync
    - lua
  tags:
    - manjaro

- name: Install imapfilter package using yay
  ansible.builtin.command:
    cmd: yay -S --answerdiff n --answerclean y imapfilter
  register: imapfilter_install
  tags:
    - manjaro

- name: Create the Mail directories
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
  loop:
    - ~/Mail
    - ~/Mail/macapinlac.com
    - ~/Mail/boogienet.com
  tags:
    - ubuntu
    - manjaro

