- name: Remove default Gnome video (totem)
  become: yes
  pacman:
    name: "{{item}}"
    state: absent
  loop:
    - totem
    - totem-plugins

#- name: Install media tools
#  become: yes
#  community.general.flatpak:
#    name:
#      - org.videolan.VLC
#      - com.ktechpit.wonderwall
#      - tech.feliciano.pocket-casts

- name: Install media tools
  become: yes
  pacman:
    name:
      - vlc

- name: Install music tools
  become: yes
  pacman:
    name:
      - mpd
      - ncmpcpp
