- name: Install core tools
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - curl
    - vim
    - base-devel
    #- xvfb
    #- software-properties-common
    #- apt-transport-https
    - git
    #- dirmngr
    - nodejs
    - npm
    #- rcm
    #- https://aur.archlinux.org/packages/rcm/
    #- neofetch
    - fastfetch
    - autorandr
    #- fd-find
    #- pipx
    - syncthing
    #- wireguard

#- name: Install pywal (pipx)
#  community.general.pipx:
#    name: pywal

- name: Clone Yay repository
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '/tmp/yay'
    clone: yes

- name: Build and install Yay
  ansible.builtin.command:
    chdir: '/tmp/yay'
    cmd: 'makepkg -si --noconfirm'

- name: Remove temporary directory
  ansible.builtin.file:
    path: '/tmp/yay'
    state: absent

- name: Install rcup
  kewlfft.aur.aur:
    use: makepkg
    state: present
    name:
      - rcm 

- name: Setup rcup with github dotfiles
  ansible.builtin.command: env RCRC=$HOME/workspace/dots/rcrc rcup -f
  register: rcup_output
