- name: Install core tools
  become: true
  pacman:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - curl
    - vim
    - base-devel
    #- xvfb
    #- software-properties-common
    #- apt-transport-https
    - git
    - zsh
    #- dirmngr
    - nodejs
    - npm
    #- rcm
    #- https://aur.archlinux.org/packages/rcm/
    #- neofetch
    - autorandr
    #- fd-find
    #- pipx
    - syncthing
    #- wireguard

#- name: Install pywal (pipx)
#  community.general.pipx:
#    name: pywal

- name: Change Ritchie's shell to zsh
  become: true
  user:
    name: ritchie
    shell: /bin/zsh

- name: Is oh-my-zsh installed
  ansible.builtin.file:
    path: ~/.oh-my-zsh
    force: yes
    state: absent

- name: Download oh-my-zsh installer
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install.sh

- name: Install oh-my-zsh
  ansible.builtin.command:
    cmd: sh /tmp/install.sh
    creates: ~/.oh-my-zsh
  register: ohmyzsh_installer

- name: Clone Yay repository
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '/tmp/yay'
    clone: yes

#- name: Change ownership of yay directory
#  ansible.builtin.file:
#    path: '/tmp/yay'
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#    recurse: yes
- name: Build and install Yay
  ansible.builtin.command:
    chdir: '/tmp/yay'
    cmd: 'makepkg -si --noconfirm'

- name: Remove temporary directory
  ansible.builtin.file:
    path: '/tmp/yay'
    state: absent

- name: Install rcup
  kewlfft.aur.aur:
    use: makepkg
    state: present
    name:
      - rcm 

- name: Setup rcup with github dotfiles
  ansible.builtin.command: env RCRC=$HOME/workspace/dots/rcrc rcup -f
  register: rcup_output
